---
Name: shopbraintree
---
Injector:
  SilverShop\Checkout\Component\OnsitePayment:
    class: StripePaymentCheckoutComponent
#GatewayInfo:
#  Braintree:
#    parameters:
#      token_key: payment_method_nonce
